### ISSUE TITLE
Project dependencies are a bit old

### ISSUE THREAD

**Issue by jconti** [cemerick/drawbridge#21]
In my environment, I need drawbridge to put a special auth token header on every request (a secret-key JWT).  This was accomplished by loading clj-http and changing the default middleware.  I needed to go look at the code for the clj-http 0.3.6 since it no longer matches the docs in that area.

clj-http 0.3.6 is from five years ago.  That is one old dependency.  Any reason drawbridge's dependencies are so far out of date?

**Comment by cemerick** [comment]
No particular reason. But, unless there's API breakage going on that makes drawbridge (or any other project IMO) not work with newer revs of its dependencies, then bumping dependency versions is not a solution to anything.

i.e. if you need a newer rev of clj-http, you should declare that locally instead of relying upon it appearing ambiently because of other libraries. (After all, drawbridge could stop using clj-http at any time, for example.) Your local dependency versions will always override transitive versions.

**Comment by jconti** [comment]
I think your logic is reasonable. I am not expert in the area of maven and its dependency algorithm, however I am seeing some weirdness with the routing macro `ANY` in compojure (it must be replaced with `(make-route nil)` to get drawbridge working).  

The output of `lein deps +tree` might be showing the opposite of the behavior you describe.  An old `ring/ring-core` looks like it is being chosen:

```
[com.cemerick/drawbridge "0.0.7"] -> [ring/ring-core "1.0.2"]
 overrides
[compojure "1.6.0"] -> [ring/ring-core "1.6.0"]

Consider using these exclusions:
[compojure "1.6.0" :exclusions [ring/ring-core]]

[com.cemerick/drawbridge "0.0.7"] -> [ring/ring-core "1.0.2"]
 overrides
[compojure "1.6.0"] -> [ring/ring-core "1.6.0"]

Consider using these exclusions:
[compojure "1.6.0" :exclusions [ring/ring-core]]
```
